sudo: false # use new container
language: c

branches:
  except: /^(gh-pages|v[0-9]\..*)/

compiler:
  - clang
  - gcc
  - g++

addons:
  apt:
    packages:
      - nasm
      - gcc-multilib
      - g++-multilib

env:
  - CONF_FLAGS=""
  - CONF_FLAGS="--without-simd"
  - CONG_FLAGS="--host=i686-linux CFLAGS=-m32 LDFLAGS=-m32"

script:
  - ./bootstrap
  - ./configure $CONF_FLAGS
  - make CFLAGS="-O2 -Wall -Wwrite-strings -Werror"
  - make distcheck
